#pragma kernel Draw

RWTexture2D<float4> Result;
Texture2D<float4> ImageInput;

float2 DrawPoint;
float BrushSize;
float4 Color;

[numthreads(8,8,1)]
void Draw (uint3 id : SV_DispatchThreadID)
{
    float distSqr = pow(DrawPoint.r - id.x, 2) + pow(DrawPoint.g - id.y, 2);

    float4 result;
    
    if(pow(BrushSize,2)>distSqr)
    {
        result = Color.rgba;
    }
    else
    {
        result = ImageInput[id.xy].rgba;
    }

    Result[id.xy] = result;
}
